export const APPLICATION_ROOT_OPENING_TAG = '<main id="application">';
export const APPLICATION_ROOT_CLOSING_TAG = '</main>';
export const APPLICATION_ROOT_TAG = APPLICATION_ROOT_OPENING_TAG + APPLICATION_ROOT_CLOSING_TAG;